name: achievement_view
description: Toast to show Achievements
version: 0.0.1
author: Rafael Almeida Barbosa
homepage: https://github.com/RafaelBarbosatec

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
